MCID=G_CUSER
DECLARE INTEGER ShellExecute IN shell32.dll ; 
 INTEGER hndWin, STRING cAction, STRING cFileName, ; 
 STRING cParams, STRING cDir, INTEGER nShowWin
 cFileName ="SQLPLUS" 
 cAction = "open" 
 CDIR=""
 MDIRNO='\'+DIRPATH+'\PRIMARY_KEY.TXT'
 CPARAMS="&MCID/&MCID@XE @&MDIRNO"
 *MESSAGEBOX(CACTION+' '+CFILENAME+' '+CPARAMS+''+CDIR)
 ShellExecute(0,cAction,cFileName,CPARAMS,CDIR,1)
 MESSAGEBOX('DONE');
 