MVAR='DROP VIEW TAKAJA'
If SQLExec(GNCONNHANDLE,Mvar) <=0 
			                  =Aerror(laArr)
			                  Messagebox(MVAR+' '+laArr(2))
ENDIF
*
MVAR="CREATE VIEW TAKAJA AS SELECT A.COMP_CODE,A.BILL_dATE,A.BILL_NO,A.B_TYPE,A.CODE,MAX(F.NAME) NAME,"+;
     "MAX(F.CITY) CITY,SUM(NVL(QNTY,0)) QNTY,SUM(NVL(WEIGHT,0)) WEIGHT,"+;
     "SUM(NVL(DR_AMT,0)) DR_AMT,SUM(NVL(CR_AMT,0)) CR_AMT,"+;
     "SUM(NVL(A.DR_AMT,0)-NVL(A.CR_AMT,0)) BILL_AMT,"+;
     "MAX(A.BK_CODE) BK_CODE,MAX(G.NAME) B_NAME,MAX(A.VR_TYPE) VR_TYPE,"+;
     "MAX((SELECT MAX(NVL(DAYS,0)) FROM BILLS B WHERE A.COMP_CODE=B.COMP_CODE AND A.CODE=B.CODE "+; 
     "AND A.BILL_DATE=B.BILL_dATE AND A.BILL_NO=B.BILL_NO AND A.B_TYPE=B.B_TYPE AND B.VR_TYPE='SL')) N_DAYS,"+;
     "MAX((SELECT MAX(V_DATE) FROM BILLS C WHERE A.COMP_CODE=C.COMP_CODE AND A.CODE=C.CODE "+;
     "AND A.BILL_DATE=C.BILL_dATE AND A.BILL_NO=C.BILL_NO AND A.B_TYPE=C.B_TYPE AND C.VR_TYPE='SL')) N_V_DATE,"+;
     "MAX((SELECT MAX(DAMI) FROM BILLS D WHERE A.COMP_CODE=D.COMP_CODE AND A.CODE=D.CODE "+;
     "AND A.BILL_DATE=D.BILL_dATE AND A.BILL_NO=D.BILL_NO AND A.B_TYPE=D.B_TYPE AND D.VR_TYPE='SL')) N_DAMI,"+;     
     "MAX((SELECT MAX(ITEM_CODE) FROM BILLS E WHERE A.COMP_CODE=E.COMP_CODE AND A.CODE=E.CODE "+;
     "AND A.BILL_DATE=E.BILL_dATE AND A.BILL_NO=E.BILL_NO AND A.B_TYPE=E.B_TYPE AND E.VR_TYPE='SL')) N_ITEM_CODE "+;         
     "FROM BILLS A,MASTER F,MASTER G WHERE SUBSTR(A.CODE,1,1)='C' AND "+;
     "(A.COMP_CODE=F.COMP_CODE AND A.CODE=F.CODE) AND "+;
     "(A.COMP_CODE=G.COMP_CODE (+) AND A.BK_CODE=G.CODE (+)) "+;
     "GROUP BY A.COMP_CODE,A.BILL_DATE,A.BILL_NO,A.B_TYPE,A.CODE "

If SQLExec(GNCONNHANDLE,Mvar) <=0 
			                  =Aerror(laArr)
			                  Messagebox(MVAR+' '+laArr(2))
ENDIF
*
MCID=RTRIM(G_CUSER)
DECLARE INTEGER ShellExecute IN shell32.dll ; 
INTEGER hndWin, STRING cAction, STRING cFileName, ; 
STRING cParams, STRING cDir, INTEGER nShowWin
cFileName ="SQLPLUS" 
cAction = "open" 
CDIR=""
MDIRNO='\'+DIRPATH+'\TAKAJAFUN.TXT'
CPARAMS="&MCID/&MCID@XE @&MDIRNO"
*MESSAGEBOX(CACTION+' '+CFILENAME+' '+CPARAMS+''+CDIR)
ShellExecute(0,cAction,cFileName,CPARAMS,CDIR,1)
*
MESSAGEBOX('DONE')  